#define FLOW_TAP_TERM 80
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 30

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "mQYEq/eaqbrJ"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 4

#define TAPPING_TERM_PER_KEY
