#define FLOW_TAP_TERM 80
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 30

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "XlrwM/9DRP63"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 2

#define TAPPING_TERM_PER_KEY
